# Site settings
title: Mauro Barbosa (mauroba)
description: Porque el conocimiento ocupa espacio. Aquí encontrarán mis experiencias con la tecnología. ¿Diario de un Nerd? ¡Adelante, pasen!
url: 'http://mauroba.tk'
baseurl: ''
google_analytics: 'UA-97096903-1'
# disqus_shortname: 'mauroba'

author:
  name: 'Mauro Barbosa'
  email: mauroba@gmail.com
  twitter_username: MauroDBarbosa
  # facebook_username: joshgerdes
  # github_username:  joshgerdes
  linkedin_username:  maurodbarbosa

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge


kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jemoji']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

port: 4001
